/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HomeDashboardRouteImport } from './routes/_home/dashboard'
import { Route as HomeDashboardIndexRouteImport } from './routes/_home/dashboard.index'
import { Route as HomeDashboardProfileRouteImport } from './routes/_home/dashboard.profile'
import { Route as HomeDashboardListRouteImport } from './routes/_home/dashboard.list'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeDashboardRoute = HomeDashboardRouteImport.update({
  id: '/_home/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeDashboardIndexRoute = HomeDashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HomeDashboardRoute,
} as any)
const HomeDashboardProfileRoute = HomeDashboardProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => HomeDashboardRoute,
} as any)
const HomeDashboardListRoute = HomeDashboardListRouteImport.update({
  id: '/list',
  path: '/list',
  getParentRoute: () => HomeDashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof HomeDashboardRouteWithChildren
  '/dashboard/list': typeof HomeDashboardListRoute
  '/dashboard/profile': typeof HomeDashboardProfileRoute
  '/dashboard/': typeof HomeDashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard/list': typeof HomeDashboardListRoute
  '/dashboard/profile': typeof HomeDashboardProfileRoute
  '/dashboard': typeof HomeDashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/_home/dashboard': typeof HomeDashboardRouteWithChildren
  '/_home/dashboard/list': typeof HomeDashboardListRoute
  '/_home/dashboard/profile': typeof HomeDashboardProfileRoute
  '/_home/dashboard/': typeof HomeDashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/dashboard'
    | '/dashboard/list'
    | '/dashboard/profile'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/dashboard/list' | '/dashboard/profile' | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/_home/dashboard'
    | '/_home/dashboard/list'
    | '/_home/dashboard/profile'
    | '/_home/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  HomeDashboardRoute: typeof HomeDashboardRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_home/dashboard': {
      id: '/_home/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof HomeDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_home/dashboard/': {
      id: '/_home/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof HomeDashboardIndexRouteImport
      parentRoute: typeof HomeDashboardRoute
    }
    '/_home/dashboard/profile': {
      id: '/_home/dashboard/profile'
      path: '/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof HomeDashboardProfileRouteImport
      parentRoute: typeof HomeDashboardRoute
    }
    '/_home/dashboard/list': {
      id: '/_home/dashboard/list'
      path: '/list'
      fullPath: '/dashboard/list'
      preLoaderRoute: typeof HomeDashboardListRouteImport
      parentRoute: typeof HomeDashboardRoute
    }
  }
}

interface HomeDashboardRouteChildren {
  HomeDashboardListRoute: typeof HomeDashboardListRoute
  HomeDashboardProfileRoute: typeof HomeDashboardProfileRoute
  HomeDashboardIndexRoute: typeof HomeDashboardIndexRoute
}

const HomeDashboardRouteChildren: HomeDashboardRouteChildren = {
  HomeDashboardListRoute: HomeDashboardListRoute,
  HomeDashboardProfileRoute: HomeDashboardProfileRoute,
  HomeDashboardIndexRoute: HomeDashboardIndexRoute,
}

const HomeDashboardRouteWithChildren = HomeDashboardRoute._addFileChildren(
  HomeDashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  HomeDashboardRoute: HomeDashboardRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
