// Русские названия стран для geojson world-atlas (countries-110m)
// Ключ — значение поля `properties.name` из topojson; значение — отображаемое имя на русском.
export const COUNTRY_NAME_RU_BY_EN: Record<string, string> = {
  Afghanistan: "Афганистан",
  Albania: "Албания",
  Algeria: "Алжир",
  Angola: "Ангола",
  Antarctica: "Антарктида",
  Argentina: "Аргентина",
  Armenia: "Армения",
  Australia: "Австралия",
  Austria: "Австрия",
  Azerbaijan: "Азербайджан",
  Bahamas: "Багамы",
  Bangladesh: "Бангладеш",
  Belarus: "Беларусь",
  Belgium: "Бельгия",
  Belize: "Белиз",
  Benin: "Бенин",
  Bhutan: "Бутан",
  Bolivia: "Боливия",
  "Bosnia and Herz.": "Босния и Герцеговина",
  Botswana: "Ботсвана",
  Brazil: "Бразилия",
  Brunei: "Бруней",
  Bulgaria: "Болгария",
  "Burkina Faso": "Буркина-Фасо",
  Burundi: "Бурунди",
  Cambodia: "Камбоджа",
  Cameroon: "Камерун",
  Canada: "Канада",
  "Central African Rep.": "Центральноафриканская Республика",
  Chad: "Чад",
  Chile: "Чили",
  China: "Китай",
  Colombia: "Колумбия",
  Congo: "Республика Конго",
  "Costa Rica": "Коста-Рика",
  Croatia: "Хорватия",
  Cuba: "Куба",
  Cyprus: "Кипр",
  Czechia: "Чехия",
  "Côte d'Ivoire": "Кот-д’Ивуар",
  "Dem. Rep. Congo": "Демократическая Республика Конго",
  Denmark: "Дания",
  Djibouti: "Джибути",
  "Dominican Rep.": "Доминиканская Республика",
  Ecuador: "Эквадор",
  Egypt: "Египет",
  "El Salvador": "Сальвадор",
  "Eq. Guinea": "Экваториальная Гвинея",
  Eritrea: "Эритрея",
  Estonia: "Эстония",
  Ethiopia: "Эфиопия",
  "Falkland Is.": "Фолклендские острова",
  Fiji: "Фиджи",
  Finland: "Финляндия",
  "Fr. S. Antarctic Lands": "Французские Южные и Антарктические территории",
  France: "Франция",
  Gabon: "Габон",
  Gambia: "Гамбия",
  Georgia: "Грузия",
  Germany: "Германия",
  Ghana: "Гана",
  Greece: "Греция",
  Greenland: "Гренландия",
  Guatemala: "Гватемала",
  Guinea: "Гвинея",
  "Guinea-Bissau": "Гвинея-Бисау",
  Guyana: "Гайана",
  Haiti: "Гаити",
  Honduras: "Гондурас",
  Hungary: "Венгрия",
  Iceland: "Исландия",
  India: "Индия",
  Indonesia: "Индонезия",
  Iran: "Иран",
  Iraq: "Ирак",
  Ireland: "Ирландия",
  Israel: "Израиль",
  Italy: "Италия",
  Jamaica: "Ямайка",
  Japan: "Япония",
  Jordan: "Иордания",
  Kazakhstan: "Казахстан",
  Kenya: "Кения",
  Kosovo: "Косово",
  Kuwait: "Кувейт",
  Kyrgyzstan: "Кыргызстан",
  Laos: "Лаос",
  Latvia: "Латвия",
  Lebanon: "Ливан",
  Lesotho: "Лесото",
  Liberia: "Либерия",
  Libya: "Ливия",
  Lithuania: "Литва",
  Luxembourg: "Люксембург",
  Macedonia: "Северная Македония",
  Madagascar: "Мадагаскар",
  Malawi: "Малави",
  Malaysia: "Малайзия",
  Mali: "Мали",
  Mauritania: "Мавритания",
  Mexico: "Мексика",
  Moldova: "Молдова",
  Mongolia: "Монголия",
  Montenegro: "Черногория",
  Morocco: "Марокко",
  Mozambique: "Мозамбик",
  Myanmar: "Мьянма",
  "N. Cyprus": "Северный Кипр",
  Namibia: "Намибия",
  Nepal: "Непал",
  Netherlands: "Нидерланды",
  "New Caledonia": "Новая Каледония",
  "New Zealand": "Новая Зеландия",
  Nicaragua: "Никарагуа",
  Niger: "Нигер",
  Nigeria: "Нигерия",
  "North Korea": "Северная Корея",
  Norway: "Норвегия",
  Oman: "Оман",
  Pakistan: "Пакистан",
  Palestine: "Палестина",
  Panama: "Панама",
  "Papua New Guinea": "Папуа — Новая Гвинея",
  Paraguay: "Парагвай",
  Peru: "Перу",
  Philippines: "Филиппины",
  Poland: "Польша",
  Portugal: "Португалия",
  "Puerto Rico": "Пуэрто-Рико",
  Qatar: "Катар",
  Romania: "Румыния",
  Russia: "Россия",
  Rwanda: "Руанда",
  "S. Sudan": "Южный Судан",
  "Saudi Arabia": "Саудовская Аравия",
  Senegal: "Сенегал",
  Serbia: "Сербия",
  "Sierra Leone": "Сьерра-Леоне",
  Slovakia: "Словакия",
  Slovenia: "Словения",
  "Solomon Is.": "Соломоновы Острова",
  Somalia: "Сомали",
  Somaliland: "Сомалиленд",
  "South Africa": "ЮАР",
  "South Korea": "Южная Корея",
  Spain: "Испания",
  "Sri Lanka": "Шри-Ланка",
  Sudan: "Судан",
  Suriname: "Суринам",
  Sweden: "Швеция",
  Switzerland: "Швейцария",
  Syria: "Сирия",
  Taiwan: "Тайвань",
  Tajikistan: "Таджикистан",
  Tanzania: "Танзания",
  Thailand: "Таиланд",
  "Timor-Leste": "Восточный Тимор",
  Togo: "Того",
  "Trinidad and Tobago": "Тринидад и Тобаго",
  Tunisia: "Тунис",
  Turkey: "Турция",
  Turkmenistan: "Туркменистан",
  Uganda: "Уганда",
  Ukraine: "Украина",
  "United Arab Emirates": "ОАЭ",
  "United Kingdom": "Великобритания",
  "United States of America": "США",
  Uruguay: "Уругвай",
  Uzbekistan: "Узбекистан",
  Vanuatu: "Вануату",
  Venezuela: "Венесуэла",
  Vietnam: "Вьетнам",
  "W. Sahara": "Западная Сахара",
  Yemen: "Йемен",
  Zambia: "Замбия",
  Zimbabwe: "Зимбабве",
  eSwatini: "Эсватини",
}
